import EmblaCarousel from "embla-carousel/components";
import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Carousel from "../components/Carousel";
import Header from "../components/Header";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Church Farm Pumpkins</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Carousel />
    </>
  );
};

export default Home;
